syntax = "proto3";

package Auth;

import "google/protobuf/empty.proto";

service Auth {
    rpc UniqueValidate(Email) returns(IsValid) {};
    rpc Signup(SignupRequest) returns (SignupResponse) {};
    rpc GetBloomFromPeer(google.protobuf.Empty) returns (BloomResponseFromPeer) {};
}

message Email{
    string email = 1;
}

message BloomResponseFromPeer {
    bytes bloom = 1;
}

message IsValid{
    bool exists = 1;
    optional bool is_active = 2;
}

message SignupRequest{
    string email = 1;
    string password = 2;
    bool is_validated = 3;
}

message SignupResponse{
    string status = 1;
}
