services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Django_Img/Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000

  django_grpc:
    container_name: django_grpc
    build:
      context: .
      dockerfile: Django_grpc_Img/Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - 50051:50051