# (bloom_manager.py)
BLOOM_SIZE = 1000
BLOOM_ERROR_RATE = 0.001
BASE_REDISS_BACKOFF = 0.5
MAX_REDISS_RETRIES = 5
BASE_PEER_BACKOFF = 0.5
MAX_PEER_RETRIES = 5

# (services.py)
MAX_DB_RETRIES = 3
BASE_DB_BACKOFF = 0.5

# (utils.py)
BASE_MEMCACHED_BACKOFF = 0.2
MAX_MEMCACHED_RETRIES = 5
MEMCACHED_CONNECTION_TIMEOUT = 0.05
SYNC_MEMCACHED_TIMEOUT = 0.2
MEMCACHED_POOL_SIZE = 3
ASYNC_MEMCACHED_SEND_TIMEOUT = 20
ASYNC_MEMCACHED_RECV_TIMEOUT = 300

# (services.py)
MAX_THREAD_COUNT = 5
SEMAPHORE_COUNT = 5
MEMCACHED_USER_ACTIVE_STATUS_TTL = 10
MEMCACHED_COMPRESSED_BLOOM_KEY = b"compressed_bloom"
BASE_MEMCACHED_ALREADY_COMPRESSING_BACKOFF = 0.5
MAX_MEMCACHED_ALREADY_COMPRESSING_RETRIES = 5
COMPRESSED_BLOOM_TTL = 60
BLOOM_COMPRESSION_LOCK_KEY = b"bloom_compression_lock"
BLOOM_COMPRESSION_LOCK_TTL = 10

# (server.py)
MINIMUM_POSTGRESQL_ASYNC_POOL_SIZE = 5
MAXIMUM_POSTGRESQL_ASYNC_POOL_SIZE = 20