# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x41uth\"\x16\n\x05\x45mail\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"?\n\x07IsValid\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x16\n\tis_active\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x0c\n\n_is_active\"F\n\rSignupRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x14\n\x0cis_validated\x18\x03 \x01(\x08\" \n\x0eSignupResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2m\n\x04\x41uth\x12.\n\x0eUniqueValidate\x12\x0b.Auth.Email\x1a\r.Auth.IsValid\"\x00\x12\x35\n\x06Signup\x12\x13.Auth.SignupRequest\x1a\x14.Auth.SignupResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAIL']._serialized_start=20
  _globals['_EMAIL']._serialized_end=42
  _globals['_ISVALID']._serialized_start=44
  _globals['_ISVALID']._serialized_end=107
  _globals['_SIGNUPREQUEST']._serialized_start=109
  _globals['_SIGNUPREQUEST']._serialized_end=179
  _globals['_SIGNUPRESPONSE']._serialized_start=181
  _globals['_SIGNUPRESPONSE']._serialized_end=213
  _globals['_AUTH']._serialized_start=215
  _globals['_AUTH']._serialized_end=324
# @@protoc_insertion_point(module_scope)
