# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import authRediss_pb2 as authRediss__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in authRediss_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthRedissStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBloomFromRediss = channel.unary_unary(
                '/AuthRediss.AuthRediss/GetBloomFromRediss',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=authRediss__pb2.BloomResponseFromRediss.FromString,
                _registered_method=True)


class AuthRedissServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBloomFromRediss(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthRedissServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBloomFromRediss': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBloomFromRediss,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=authRediss__pb2.BloomResponseFromRediss.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthRediss.AuthRediss', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AuthRediss.AuthRediss', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthRediss(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBloomFromRediss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthRediss.AuthRediss/GetBloomFromRediss',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            authRediss__pb2.BloomResponseFromRediss.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
