# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authRediss.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'authRediss.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61uthRediss.proto\x12\nAuthRediss\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x17\x42loomResponseFromRediss\x12\r\n\x05\x62loom\x18\x01 \x01(\x0c\x32\x61\n\nAuthRediss\x12S\n\x12GetBloomFromRediss\x12\x16.google.protobuf.Empty\x1a#.AuthRediss.BloomResponseFromRediss\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authRediss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOOMRESPONSEFROMREDISS']._serialized_start=61
  _globals['_BLOOMRESPONSEFROMREDISS']._serialized_end=101
  _globals['_AUTHREDISS']._serialized_start=103
  _globals['_AUTHREDISS']._serialized_end=200
# @@protoc_insertion_point(module_scope)
